### ISSUE TITLE
Where is the train.py and the model code?

### ISSUE THREAD

**Issue by HC-Guo** [rxn4chemistry/rxn-standardization#2]
here i want to reproduce the results and modify the model in the paper, however, i can not get the model file from the repo, also i feel confused that only preprocess python files are provided..

**Comment by mirunacrt** [comment]
Hi @HC-Guo, thanks for your interest in our work.

The model comes directly from OpenNMT, and you can run the training with the `onmt_train` command, following the instructions in the README: https://github.com/rxn4chemistry/rxn-standardization#training.

**Comment by HC-Guo** [comment]
thanks, i will try.
