### ISSUE TITLE
Could you provide which part of PubChem that you used for pre-training ? 

### ISSUE THREAD

**Issue by HC-Guo** [rxn4chemistry/rxn-standardization#3]
Thanks, i have few questions.
1. The instructions for using the PubChem in this section are too abbreviated, The pre-training data should be more clear.
2. Could you provide the pre-processed csv files?
3. Could you give a brief introduction about the process on how to select the pretrained data? because there are too many folders in this two links: https://ftp.ncbi.nlm.nih.gov/pubchem/Substance/, https://ftp.ncbi.nlm.nih.gov/pubchem/Compound/. 
4. If the data for pre-training can not be confirmed clearly, the results in the paper are not that convincing. i suggest the authors give a detailed instruction for reproducing the results. Thus this work can be followed by us easily.

**Comment by mirunacrt** [comment]
Hi @HC-Guo, 

Thanks for pointing this out, we will provide more detailed instructions in the coming weeks. Until then, we encourage you to run the pipeline with 200k compounds selected randomly from PubChem. The `SID-Map`, 'CID-Smiles` and Substance `SDF` files for all the PubChem entries to date are available under `Extras` in the linked websites (https://ftp.ncbi.nlm.nih.gov/pubchem/Substance/, https://ftp.ncbi.nlm.nih.gov/pubchem/Compound/).

The release of the pre-processed CSV files is also under way.

**Comment by mirunacrt** [comment]
Hi @HC-Guo,

Coming back to you regarding this issue -- the pre-trained model and the data used for pre-training are now available at https://zenodo.org/record/7842044#.ZD65Zy8Rr0p. We also revisited the instructions in the README. Please let us know if anything is still unclear.
